# Generated by Django 6.0.6 on 2026-06-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="guest_id",
            field=models.UUIDField(
                blank=True, db_index=True, default=None, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("guest_id__isnull", True), ("user__isnull", False)),
                    models.Q(("guest_id__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="cart_has_user_or_guest_id_not_both",
            ),
        ),
    ]
